### ISSUE TITLE
Add citation file

### ISSUE THREAD

**Issue by YoniSchirris** [NKI-AI/dlup#158]
DLUP is up to a standard where it is used extensively throughout projects and published works. 

It would be preferred to properly reference the software instead of providing a github url in footnotes in papers.

It is described here (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) how to do this. 

In our case, I'd recommend adding a `CITATION.cff` that looks like follows;

```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: "Teuwen"
  given-names: "Jonas"
  orcid: "https://orcid.org/0000-0002-1825-1428"
- family-names: "Romor"
  given-names: "Leonardo"
- family-names: "Pai"
  given-names: "Ajey"
  orcid: "https://orcid.org/0009-0003-3970-9236"
- family-names: "Schirris"
  given-names: "Yoni"
  orcid: "https://orcid.org/0000-0003-0217-8737" 
title: "DLUP: Deep Learning Utilities for Pathology"
version: 0.3.25
date-released: 2023-05-12
url: "https://github.com/nki-ai/dlup"
```
